// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezwbkopecczisqxkbqoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6d2Jrb3BlY2N6aXNxeGticW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTI2MTksImV4cCI6MjA2OTg2ODYxOX0.zkrwsajarWw7BjHTXUnnIVrjukdol2kj3R1XuyCUoKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});